all:
  children:
    debian_vms:
      hosts:
        debian-soc:
          ansible_host: 192.168.64.9
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/debian-soc
          ansible_python_interpreter: /usr/bin/python3

