[book]
authors = ["Viacheslav"]
language = "en"
src = "src"
title = "Masterschool Final Project"

[output.html]
additional-css = ["./theme/css/custom.css"]

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0

[output.html.print]
enable = false
